Portfolio Finish Mobile Project
tamoorsaeed22/Portfolio-Finish-Mobile pull request #1
Opened 2023-01-18 14:07 UTC by tamoorsaeed22

Summary :
Used flex for both sessions.
Used Microverse template 2 for reference.
The used mobile-first CSS model 
Used grid and flex as per instruction.
Following Mobile's first model.
Created contact form and footer as per Figma template.

2023-01-18 14:34 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️
Hi @tamoorsaeed22 , 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 14:34 UTC, bobb-Rob commented on index.html
> +                    <h2 class="title">About Me</h2>
_I must admit that you have done exceptionally well on this project. Your work is very beautiful and almost the same with the Figma design. Well done 👏_ 

However, some little things needs to be done to further improve your work. 

- [ ] I noticed that you declared the correct `font-family` for your about age title but the font type did not affect the text at run time. The reason is that you have not imported this font into your CSS file. Use google font @import for this. 
- [ ] The background illustration in this section is overlapping a little bit with the border-bottom of its container. Please compare your work and Figma design and make adjustments.

Your Work
![image](https://user-images.githubusercontent.com/84156714/213197334-01de487a-6853-4e95-9f49-c601aaa487c4.png)

Figma design
![image](https://user-images.githubusercontent.com/84156714/213197508-eb2f6472-ccb3-42b1-9147-e5b90f6be5c8.png)

2023-01-18 14:34 UTC, bobb-Rob commented on index.html
> +        </footer>
- [ ] [REQUIRED] Please remove this contact section as it is not part of this milestone for this project. You do this contact section in the next milestone.

2023-01-19 07:17 UTC, iambenkis approved these changes
Hi @tamoorsaeed22 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![ ](https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)
## Highlights
Linters are passing 👍 
The project is running successfully 👍 
PR is well descriptive 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@iambenkis** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 07:17 UTC, iambenkis commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] [**OPTIONAL**] Good job setting up the README file :smile: , however you should remove this text so that your README looks professional, :+1:

2023-01-19 07:26 UTC, merged